# Generated by Django 2.2 on 2019-04-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default_columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_updated', models.DateTimeField(auto_now_add=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='adProperty',
            fields=[
                ('default_columns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Myads.default_columns')),
                ('Adid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slot_Name', models.CharField(max_length=20)),
                ('slot_from', models.DateTimeField(max_length=20)),
                ('slot_to', models.DateTimeField(max_length=20)),
                ('open_for_bid', models.BooleanField(default=True)),
            ],
            bases=('Myads.default_columns',),
        ),
    ]
