# Generated by Django 2.2 on 2019-04-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='default_columns',
            old_name='verified',
            new_name='Valid',
        ),
    ]
