# Generated by Django 2.2 on 2019-04-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myads', '0003_adproperty_default_bid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adproperty',
            old_name='default_bid_price',
            new_name='min_bid_price',
        ),
    ]
