# Generated by Django 2.2 on 2019-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myads', '0004_auto_20190413_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adproperty',
            name='min_bid_price',
            field=models.FloatField(),
        ),
    ]
