# Generated by Django 2.2 on 2019-04-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Myads', '0005_auto_20190413_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='biddings',
            fields=[
                ('default_columns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Myads.default_columns')),
                ('bid_price', models.FloatField()),
                ('Adid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myads.adProperty')),
            ],
            bases=('Myads.default_columns',),
        ),
    ]
