# Generated by Django 2.2 on 2019-04-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddings',
            name='bidder',
            field=models.CharField(default='Paris', max_length=20),
        ),
    ]
