# Generated by Django 2.2 on 2019-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddings', '0002_biddings_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddings',
            name='bidder',
            field=models.CharField(max_length=20),
        ),
    ]
